name: Build Snapshot

on:
  push:
    branches:
      - '**'
      # don't run on dependabot branches. Dependabot will create pull requests, which will then be run instead
      - '!dependabot/**'
  workflow_dispatch:
  schedule:
    # build it monthly: At 04:15 on day-of-month 1.
    - cron: '15 4 1 * *'
    # for testing the event "schedule": run every 15 minutes starting from minute 5 through 59 (0, 15, 30, 45)
    #- cron: '0/15 * * * *'

jobs:
  build:
    name: Build Snapshot
    uses: ./.github/workflows/build.yml
